//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterEveOnlineSkill
    {
        public int CharacterSkillId { get; set; }
        public int CharacterId { get; set; }
        public int EveOnlineSkillId { get; set; }
        public byte Rank { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual EveOnlineSkill EveOnlineSkill { get; set; }
    }
}
