//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineSkillGroup
    {
        public EveOnlineSkillGroup()
        {
            this.EveOnlineSkills = new HashSet<EveOnlineSkill>();
        }
    
        public int EveOnlineSkillGroupId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EveOnlineSkill> EveOnlineSkills { get; set; }
    }
}
