//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineSolarSystem
    {
        public int EveOnlineSolarSystemId { get; set; }
        public int EveOnlineConstellationId { get; set; }
        public string Name { get; set; }
        public double Security { get; set; }
    
        public virtual EveOnlineConstellation EveOnlineConstellation { get; set; }
    }
}
