//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineAttribute
    {
        public EveOnlineAttribute()
        {
            this.EveOnlineSkills = new HashSet<EveOnlineSkill>();
            this.EveOnlineSkills1 = new HashSet<EveOnlineSkill>();
        }
    
        public int EveOnlineAttributeId { get; set; }
        public Nullable<int> EveOnlineIconId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string Notes { get; set; }
    
        public virtual EveOnlineIcon EveOnlineIcon { get; set; }
        public virtual ICollection<EveOnlineSkill> EveOnlineSkills { get; set; }
        public virtual ICollection<EveOnlineSkill> EveOnlineSkills1 { get; set; }
    }
}
