//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineBloodline
    {
        public int EveOnlineBloodlineId { get; set; }
        public int EveOnlineRaceId { get; set; }
        public Nullable<int> EveOnlineIconId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MaleDescription { get; set; }
        public string FemaleDescription { get; set; }
        public string ShortDescription { get; set; }
        public string ShortMaleDescription { get; set; }
        public string ShortFemaleDescription { get; set; }
    
        public virtual EveOnlineIcon EveOnlineIcon { get; set; }
        public virtual EveOnlineRace EveOnlineRace { get; set; }
    }
}
