//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineConstellation
    {
        public EveOnlineConstellation()
        {
            this.EveOnlineSolarSystems = new HashSet<EveOnlineSolarSystem>();
        }
    
        public int EveOnlineConstellationId { get; set; }
        public int EveOnlineRegionId { get; set; }
        public string Name { get; set; }
    
        public virtual EveOnlineRegion EveOnlineRegion { get; set; }
        public virtual ICollection<EveOnlineSolarSystem> EveOnlineSolarSystems { get; set; }
    }
}
