//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineRequiredSkill
    {
        public int EveOnlineRequiredSkillId { get; set; }
        public int EveOnlineSkillId { get; set; }
        public int RequiredEveOnlineSkillId { get; set; }
        public int RequiredSkillLevel { get; set; }
    
        public virtual EveOnlineSkill EveOnlineSkill { get; set; }
        public virtual EveOnlineSkill RequiredEveOnlineSkill { get; set; }
    }
}
