//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveOnlineIcon
    {
        public EveOnlineIcon()
        {
            this.EveOnlineAttributes = new HashSet<EveOnlineAttribute>();
            this.EveOnlineBloodlines = new HashSet<EveOnlineBloodline>();
            this.EveOnlineCategories = new HashSet<EveOnlineCategory>();
            this.EveOnlineFactions = new HashSet<EveOnlineFaction>();
            this.EveOnlineGroups = new HashSet<EveOnlineGroup>();
            this.EveOnlineMarketGroups = new HashSet<EveOnlineMarketGroup>();
            this.EveOnlineRaces = new HashSet<EveOnlineRace>();
            this.EveOnlineTypes = new HashSet<EveOnlineType>();
        }
    
        public int EveOnlineIconId { get; set; }
        public string FileNameWithoutExtension { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EveOnlineAttribute> EveOnlineAttributes { get; set; }
        public virtual ICollection<EveOnlineBloodline> EveOnlineBloodlines { get; set; }
        public virtual ICollection<EveOnlineCategory> EveOnlineCategories { get; set; }
        public virtual ICollection<EveOnlineFaction> EveOnlineFactions { get; set; }
        public virtual ICollection<EveOnlineGroup> EveOnlineGroups { get; set; }
        public virtual ICollection<EveOnlineMarketGroup> EveOnlineMarketGroups { get; set; }
        public virtual ICollection<EveOnlineRace> EveOnlineRaces { get; set; }
        public virtual ICollection<EveOnlineType> EveOnlineTypes { get; set; }
    }
}
