//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FallenNovaContext : DbContext
    {
        public FallenNovaContext()
            : base("name=FallenNovaContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Character> Characters { get; set; }
        public DbSet<ContactUsLog> ContactUsLogs { get; set; }
        public DbSet<Corporation> Corporations { get; set; }
        public DbSet<EveOnlineAttribute> EveOnlineAttributes { get; set; }
        public DbSet<EveOnlineBloodline> EveOnlineBloodlines { get; set; }
        public DbSet<EveOnlineCategory> EveOnlineCategories { get; set; }
        public DbSet<EveOnlineConstellation> EveOnlineConstellations { get; set; }
        public DbSet<EveOnlineFaction> EveOnlineFactions { get; set; }
        public DbSet<EveOnlineGroup> EveOnlineGroups { get; set; }
        public DbSet<EveOnlineIcon> EveOnlineIcons { get; set; }
        public DbSet<EveOnlineMarketGroup> EveOnlineMarketGroups { get; set; }
        public DbSet<EveOnlineRace> EveOnlineRaces { get; set; }
        public DbSet<EveOnlineRegion> EveOnlineRegions { get; set; }
        public DbSet<EveOnlineSolarSystem> EveOnlineSolarSystems { get; set; }
        public DbSet<EveOnlineType> EveOnlineTypes { get; set; }
        public DbSet<KillLog> KillLogs { get; set; }
        public DbSet<KillLogAttacker> KillLogAttackers { get; set; }
        public DbSet<KillLogItem> KillLogItems { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<UserLogType> UserLogTypes { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<UserStatus> UserStatuses { get; set; }
        public DbSet<CharacterEveOnlineSkill> CharacterEveOnlineSkills { get; set; }
        public DbSet<EveOnlineRequiredSkill> EveOnlineRequiredSkills { get; set; }
        public DbSet<EveOnlineSkill> EveOnlineSkills { get; set; }
        public DbSet<EveOnlineSkillGroup> EveOnlineSkillGroups { get; set; }
        public DbSet<EveOnlineSkillTree> EveOnlineSkillTrees { get; set; }
    }
}
