//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KillLog
    {
        public KillLog()
        {
            this.KillLogAttackers = new HashSet<KillLogAttacker>();
            this.KillLogItems = new HashSet<KillLogItem>();
        }
    
        public int KillLogId { get; set; }
        public int SolarSystemId { get; set; }
        public System.DateTime KillDateTime { get; set; }
        public int VictimCharacterId { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual ICollection<KillLogAttacker> KillLogAttackers { get; set; }
        public virtual ICollection<KillLogItem> KillLogItems { get; set; }
    }
}
