//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KillLogItem
    {
        public int KillLogItemId { get; set; }
        public int KillLogId { get; set; }
        public int ItemTypeId { get; set; }
        public int QuantityDropped { get; set; }
        public int QuantityDestroyed { get; set; }
    
        public virtual KillLog KillLog { get; set; }
    }
}
