//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenNova.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserLogId { get; set; }
        public int UserId { get; set; }
        public int UserLogTypeId { get; set; }
        public Nullable<int> ActionAgainstUserId { get; set; }
        public System.DateTime AddedDateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserLogType UserLogType { get; set; }
        public virtual User User1 { get; set; }
    }
}
